(ns lexicon.test-helpers
  "Convenience namespace that re-exports lexicon.semantic.helpers.

  This allows tests to use (require [lexicon.test-helpers :as helpers])
  regardless of whether they're in the semantic/ subdirectory or not."
  (:require [lexicon.semantic.helpers :as h])
  (:require-macros [lexicon.core.macros :refer [save-excursion save-current-buffer with-current-buffer]]
                   [lexicon.core.dynamic :refer [with-inhibit-read-only without-undo]]
                   [lexicon.semantic.helpers :refer [with-test-buffer]]))

;; Re-export all public functions from semantic.helpers
(def reset-editor-db! h/reset-editor-db!)
(def with-wasm h/with-wasm)
(def create-buffer h/create-buffer)
(def buffer-text h/buffer-text)
(def insert-text h/insert-text)
(def buffer-exists? h/buffer-exists?)
(def visit-file h/visit-file)
(def buffer-file h/buffer-file)
(def set-read-only h/set-read-only)
(def point h/point)
(def set-point h/set-point)
(def current-buffer h/current-buffer)
(def kill-region h/kill-region)
(def yank h/yank)
(def undo h/undo)
(def undo-boundary h/undo-boundary)
(def enable-major-mode h/enable-major-mode)
(def current-major-mode h/current-major-mode)
(def enable-minor-mode h/enable-minor-mode)
(def minor-mode-enabled? h/minor-mode-enabled?)
(def split-window-horizontally h/split-window-horizontally)
(def delete-other-windows h/delete-other-windows)
(def show-buffer-in-two-windows h/show-buffer-in-two-windows)
(def show-buffer-in-new-window h/show-buffer-in-new-window)
(def window-text h/window-text)
(def activate-minibuffer h/activate-minibuffer)
(def deactivate-minibuffer h/deactivate-minibuffer)
(def minibuffer-insert h/minibuffer-insert)
(def minibuffer-contents h/minibuffer-contents)
(def set-global-key h/set-global-key)
(def set-buffer-local-key h/set-buffer-local-key)
(def lookup-key h/lookup-key)
(def press-key-sequence h/press-key-sequence)
(def in-prefix-state? h/in-prefix-state?)
(def last-invoked-command h/last-invoked-command)
(def eval-lisp h/eval-lisp)
(def save-buffer h/save-buffer)
(def revert-buffer h/revert-buffer)
(def message h/message)
(def echo-area-text h/echo-area-text)
(def define-test-command h/define-test-command)
(def command-name h/command-name)
(def command-doc h/command-doc)
(def command-fn h/command-fn)
(def invoke-command h/invoke-command)
(def with-instrumented-dispatch h/with-instrumented-dispatch)
(def dispatch-was-used? h/dispatch-was-used?)

;; Text Properties
(def put-text-property h/put-text-property)
(def get-text-property h/get-text-property)
(def text-properties-at h/text-properties-at)
(def propertize h/propertize)
(def get-text-property-from-string h/get-text-property-from-string)
(def visible-text h/visible-text)

;; Convenience wrappers
(def insert h/insert)
(def goto-char h/goto-char)
(def delete-region h/delete-region)
(def erase-buffer h/erase-buffer)
(def buffer-name h/buffer-name)
(def buffer-read-only? h/buffer-read-only?)
(def set-buffer-read-only h/set-buffer-read-only)

;; Mark and Region
(def set-mark h/set-mark)
(def mark h/mark)
(def activate-mark h/activate-mark)
(def deactivate-mark h/deactivate-mark)
(def region-active? h/region-active?)

;; Search and Navigation
(def forward-word h/forward-word)
(def backward-word h/backward-word)
(def word-at-point h/word-at-point)
(def looking-at h/looking-at)
(def search-forward h/search-forward)

;; Narrowing
(def narrow-to-region h/narrow-to-region)

;; Hooks
(def add-hook h/add-hook)
(def remove-hook h/remove-hook)
(def run-hooks h/run-hooks)
(def run-hook-with-args-until-success h/run-hook-with-args-until-success)
(def run-hook-with-args-until-failure h/run-hook-with-args-until-failure)

;; Keymaps
(def make-keymap h/make-keymap)
(def define-key h/define-key)

;; Buffer ID
(def current-buffer-id h/current-buffer-id)
(def kill-buffer h/kill-buffer)
(def toggle-read-only h/toggle-read-only)
(def mode-line-string h/mode-line-string)
(def forward-char h/forward-char)
(def backward-char h/backward-char)
(def dired h/dired)

;; Windows
(def current-window h/current-window)
(def select-window h/select-window)
(def split-window h/split-window)

;; Markers
(def make-marker h/make-marker)
(def marker-position h/marker-position)
(def marker-buffer h/marker-buffer)
(def set-marker h/set-marker)
(def move-marker h/move-marker)
(def copy-marker h/copy-marker)
(def marker-insertion-type h/marker-insertion-type)
(def set-marker-insertion-type h/set-marker-insertion-type)
(def markerp h/markerp)
(def insert-before-markers h/insert-before-markers)
(def buffer-string h/buffer-string)

;; Kill Ring
(def kill-new h/kill-new)
(def kill-append h/kill-append)
(def current-kill h/current-kill)
(def kill-ring-length h/kill-ring-length)
(def clear-kill-ring h/clear-kill-ring)
(def yank-pop h/yank-pop)
(def kill-line h/kill-line)
(def kill-word h/kill-word)
(def backward-kill-word h/backward-kill-word)
(def copy-region-as-kill h/copy-region-as-kill)

;; Buffer Primitives (Issue #100)
(def buffer-live-p h/buffer-live-p)
(def get-buffer-create h/get-buffer-create)
(def buffer-modified-p h/buffer-modified-p)
(def set-buffer-modified-p h/set-buffer-modified-p)
(def widen h/widen)
(def save-restriction h/save-restriction)
(def set-buffer h/set-buffer)
(def rename-buffer h/rename-buffer)
(def other-buffer h/other-buffer)
(def buffer-disable-undo h/buffer-disable-undo)
(def buffer-enable-undo h/buffer-enable-undo)
(def buffer-local-value h/buffer-local-value)
(def make-local-variable h/make-local-variable)
(def setq h/setq)
(def kill-all-local-variables h/kill-all-local-variables)
(def point-min h/point-min)
(def point-max h/point-max)
(def buffer-name-from-id h/buffer-name-from-id)

;; Undo (Issue #103)
(def with-undo-group h/with-undo-group)
(def undo-history-length h/undo-history-length)
(def undo-in-region h/undo-in-region)
(def redo h/redo)

;; Editing Primitives (Issue #105)
(def bobp h/bobp)
(def eobp h/eobp)
(def bolp h/bolp)
(def eolp h/eolp)
(def char-after h/char-after)
(def char-before h/char-before)
(def delete-and-extract-region h/delete-and-extract-region)
(def buffer-substring-no-properties h/buffer-substring-no-properties)
(def region-beginning h/region-beginning)
(def region-end h/region-end)
(def line-beginning-position h/line-beginning-position)
(def line-end-position h/line-end-position)
(def buffer-substring h/buffer-substring)

;; SCI Integration (Issue #106)
(def set-prefix-arg h/set-prefix-arg)
(def sci-namespace-keys h/sci-namespace-keys)

;; Isearch (Issue #107)
(def isearch-forward h/isearch-forward)
(def isearch-forward-repeat h/isearch-forward-repeat)
(def isearch-backward h/isearch-backward)
(def query-replace h/query-replace)

;; Minibuffer/Completion (Issue #108)
(def completion-metadata h/completion-metadata)
(def all-completions h/all-completions)

;; Window Management (Issue #110)
(def split-window-vertically h/split-window-vertically)
(def delete-window h/delete-window)
(def window-count h/window-count)
(def other-window h/other-window)
(def current-window-configuration h/current-window-configuration)

;; File I/O (Issue #111)
(def find-file h/find-file)
(def file-exists-p h/file-exists-p)
(def file-directory-p h/file-directory-p)
(def file-attributes h/file-attributes)
(def buffer-file-name h/buffer-file-name)
(def directory-files h/directory-files)

;; Shell (Issue #112)
(def shell h/shell)
(def shell-send-input h/shell-send-input)
(def default-directory h/default-directory)
(def shell-previous-input h/shell-previous-input)
(def shell-current-input h/shell-current-input)

;; Version Control (Issue #113)
(def vc-backend h/vc-backend)
(def vc-state h/vc-state)
(def vc-diff h/vc-diff)
(def vc-print-log h/vc-print-log)

;; Outline/Folding (Issue #114)
(def outline-hide-subtree h/outline-hide-subtree)
(def outline-next-heading h/outline-next-heading)
(def hs-hide-block h/hs-hide-block)
(def hs-toggle-hiding h/hs-toggle-hiding)

;; Extended Packages (Issues #115-#124)
(def list-buffers h/list-buffers)
(def project-root h/project-root)
(def windmove-left h/windmove-left)
(def recentf-list h/recentf-list)
(def dabbrev-expand h/dabbrev-expand)
(def compile h/compile)
(def imenu-create-index h/imenu-create-index)
(def show-paren-data-function h/show-paren-data-function)
(def eldoc-documentation-function h/eldoc-documentation-function)
(def apropos-command h/apropos-command)
(def describe-function h/describe-function)

;; Grep & Highlighting (#125)
(def grep h/grep)
(def grep-find h/grep-find)
(def hi-lock-mode h/hi-lock-mode)
(def highlight-regexp h/highlight-regexp)

;; Remote Files / TRAMP (#126)
(def tramp-dissect-file-name h/tramp-dissect-file-name)
(def tramp-tramp-file-p h/tramp-tramp-file-p)
(def tramp-methods h/tramp-methods)

;; Terminal Emulation (#127)
(def term h/term)
(def term-line-mode h/term-line-mode)
(def term-char-mode h/term-char-mode)
(def comint-send-input h/comint-send-input)
(def comint-previous-input h/comint-previous-input)
(def ansi-color-apply h/ansi-color-apply)

;; Incremental Completion (#128)
(def icomplete-completions h/icomplete-completions)
(def icomplete-forward-completions h/icomplete-forward-completions)

;; LSP Client / Eglot (#129)
(def eglot-server-programs h/eglot-server-programs)
(def eglot-ensure h/eglot-ensure)
(def eglot-eldoc-function h/eglot-eldoc-function)
(def eglot-completion-at-point h/eglot-completion-at-point)
(def eglot-diagnostics h/eglot-diagnostics)
(def eglot-code-actions h/eglot-code-actions)

;; Font Lock & Code Intelligence (#130)
(def font-lock-keywords h/font-lock-keywords)
(def font-lock-add-keywords h/font-lock-add-keywords)
(def face-attribute h/face-attribute)
(def which-function h/which-function)

;; Macros - with-test-buffer is imported via :require-macros from lexicon.semantic.helpers
