[package]
name = "lexicon-wasm"
version = "0.1.0"
edition = "2021"
description = "WebAssembly bindings for lexicon-core text editor"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
lexicon-core = { path = "../core" }
wasm-bindgen = "0.2"
js-sys = "0.3"
console_error_panic_hook = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "Performance",
  "Window",
]

